[repository]
name = "hyprland-fix-hdr-screenshare"
authors = ["daniel"]

plugins = ["fix-hdr-screenshare"]

[fix-hdr-screenshare]
description = "Disable the HDR unmodified-copy MRT path used for screenshare"
authors = ["daniel"]
output = "fix-hdr-screenshare.so"
build = [
    "make",
]
