[repository]
name = "hyprland-fix-hdr-screenshare"
authors = ["daniel"]
commit_pins = [
    # Hyprland                                  hyprland-fix-hdr-screenshare
    ["af923e30d1d24f1f4a4f5cb8308065173c1d9539", "8f3dc00959266a347ce321211fb0c7d0d932702b"], # v0.55.0
]

[hyprland]
plugins = ["fix-hdr-screenshare"]

[fix-hdr-screenshare]
description = "Disable the HDR unmodified-copy MRT path used for screenshare"
authors = ["daniel"]
output = "fix-hdr-screenshare.so"
build = [
    "make",
]
